name: ndx-franklab-novela
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - python= {{ $TRAVIS_PYTHON_VERSION }}
  - python-dateutil
  - setuptools
  - hdmf==1.6.1
  - pynwb==1.3.0
  - pytest





