{% set data = load_setup_py_data() %}

package:
  name: ndx-franklab-novela
  version: {{ data.get('version') }}

source:
  git_url: https://github.com/NovelaNeuro/ndx-franklab-novela
  rev: user/acwikla/conda_test_version

build:
  number: 0

requirements:
  build:
    - python=={{ python --version }}
    - setuptools
    - hdmf==1.6.1
    - python-dateutil
    - pynwb==1.3.0
  run:
    - python>={{ python --version }}, <{{ python --version + 0.1.0}}
    - python-dateutil
    - hdmf==1.6.1
    - pynwb==1.3.0
    - pytest

