{% set data = load_setup_py_data() %}

package:
  name: ndx-franklab-novela
  version: {{ data.get('version') }}

source:
  git_url: https://github.com/NovelaNeuro/ndx-franklab-novela

build:
  number: 0

requirements:
  build:
    - python==3.7
    - setuptools
    - hdmf==1.6.4
    - python-dateutil
    - pynwb==1.3.3
  run:
    - python>=3.7
    - python-dateutil
    - hdmf==1.6.4
    - pynwb==1.3.3
    - pytest

